### PR TITLE
MISC: Typo Fixes (merge fixes)

### LINKED ISSUE #4174: Typo in dialog box when applying for job or working in job
See the attached images.  The problem has been around even before v2.1.0.  I don't think a save file is necessary because the problem can easily be reproduced as follows:

When working in a job:

1. Apply for a business job at a company.
2. Work your way up until your position is "Operations Manager".

Change

`You are currently working as a Operations Manager at [companyName]`

to

`You are currently working as an Operations Manager at [companyName]`

When applying for a job:

1. Apply for an IT job at a company.
2. Take note of the dialog box.

Change

`You were offered a new job at [companyName] as a IT Intern!`

to

`You were offered a new job at [companyName] as an IT Intern!`

typo
typo-2

### PR DESCRIPTION
**Pull request by Snarling**
Replacement for #4152 , with merge updates added
Fixes #4174

### CODE REVIEW

**Comment by Snarling** [comment]
@Shiiyu A couple of the fixes you had that popped up while I was merging I did not include, because the original was fine.

e.g. for "[on the off chance](https://www.merriam-webster.com/dictionary/on%20the%20off%20chance)" or "[superintelligence](https://en.wikipedia.org/wiki/Superintelligence)" you had dashes added to both.

**Comment by Snarling** [comment]
@hydroflame This fails lint test because of typo fixes in ThirdParty/JSInterpreter.js, I'm not sure why it failed prettier test because I'm not getting any formatting issues when I run npm run format.

**Comment by Shiiyu** [comment]
> @Shiiyu A couple of the fixes you had that popped up while I was merging I did not include, because the original was fine.
> 
> e.g. for "[on the off chance](https://www.merriam-webster.com/dictionary/on%20the%20off%20chance)" or "[superintelligence](https://en.wikipedia.org/wiki/Superintelligence)" you had dashes added to both.

These were fixed in later commits

**Comment by Snarling** [comment]
> > @Shiiyu A couple of the fixes you had that popped up while I was merging I did not include, because the original was fine.
> > e.g. for "[on the off chance](https://www.merriam-webster.com/dictionary/on%20the%20off%20chance)" or "[superintelligence](https://en.wikipedia.org/wiki/Superintelligence)" you had dashes added to both.
> 
> These were fixed in later commits

Gotcha, it had me merge each commit chronologically so I never knew if something made it into the final version of the file or not (well, until the end)

**Comment by quacksouls** [comment]
Do I need to review this too?  I left 2 reviews for #4152 and they both disappear from that ticket.  Perhaps I'm not needed here.  Sorry, I'm confused.  You take it from here, @Snarling?

**Comment by Snarling** [comment]
> Do I need to review this too? Perhaps I'm not needed here. Sorry, I'm confused.

@quacksouls Were there issues with the previous PR that needed addressing still? If so yes please bring them up here as well

**Comment by Snarling** [comment]
This now fixes #4174

**Comment by quacksouls** [comment]
1. Running `npm run format` didn't report any issues.

2. The linter is happy now.  Running `npm run lint` no longer complains about unused import.

3. The jester is laughing at us for failing so many tests.  Running `npm run test` reports a few 100 failed tests.
```sh
Test Suites: 5 failed, 4 passed, 9 total
Tests:       416 failed, 2 skipped, 179 passed, 597 total
Snapshots:   0 total
Time:        41.786 s
Ran all test suites.
```
Previously, I had one failed test due to PR #4141.  Perhaps the project no longer use or care about the test suite?

4. A number of glaring grammatical errors in the typo fixes.  However, those grammatical errors are not within the scope of this typo-police PR.  Grammatical errors belong to another, grammar police PR.

5. @Shiiyu has already addressed the changes proposed in my first review at #4152.
    1. 9094e5c54aba6fde9f6cc09dbc03f5a4cfc101c7 (and b029b5a1f92048ed3c47eb9aa1615009dcc20129) fix 164583c844b2577e920b8253b03b56dc9f0337d0 (and 2523eb802b7aeba138931c012d6868a5e1721eab).
    1. eef108a09f9c7c50aeb235c1a430337df517cb42 (and 9b1fdce32b02c3df6845b889cd51517e173da92c) fix 78c88be9e2ea584e8dd4c2f3ae8602599a0067f2 (and 699ca2fc7fb23db50a3b6e110a62fccb39fbf527).
    1. b13fba920031bad0568357668eb16c1238f8d272 (and 2a176cfa4db4803d6f2295d1937587ec75bcf4e2) fix 7d9a2cef1a858e3a2239a90a6d11f3545d8fe438 (and 41c76eb238923d989e51d884d962fdda0a198ef1 and 2b01c3f02fb4a896dc24c3ae98be9f10b6d26ce4).
    1. 975d0b72e46c4c97600810b5754def39bd1fb0aa (and 369d8988a1d900f7a1013cc2ab55e5bd6ad9d081) fix 51cd50a8cc7037183d788bbcefc6b7f7123b2a1b (and 4c26fbc28d37340ac1a4b3bbcd2c5adee90d80f6).
    1. 2b01ac3bff11a847559f3cbacd2f475a63c69ae6 (and 6edceca436d6a0d3c80348481d8fffcf98257776) fix 6b23e55f546879a81383a61efe4991a9897835a4 (and 79adafd753b4b6a9378468db3b2149c404f0b72f).
    1. f14f831f34ec0ef54cc822bd05a2b3d522931ce1 fixes f5154fc58f4f85e9405c20de1bafac96ba5674ad.
    1. 97b3cc4cd8978bcce3fb1b94ceee320b8525ceca fixes a9e50985cf7bbaf58005ce9a97033255d8a38752.

6. Commit 78de6f0696b5e97f049a3fbd06f342feef0ddc84 touches a test suite.  The tests ran with one failure (built via `npm run start:dev`), but unrelated to the commit:
```sh
Bitburner v2.1.0 (f21098d4)
[home ~/]> run tb_basic.script 
Running script with 1 thread(s), pid 1 and args: [].
tb_basic.script: Test run: FAILED
tb_basic.script: Test arith1: OK
tb_basic.script: Test arith2: OK
tb_basic.script: Test arith3: OK
tb_basic.script: Test arith4: OK
tb_basic.script: Test arith5: OK
tb_basic.script: Test arith6: OK
tb_basic.script: Test arith7: OK
tb_basic.script: Test logic1: OK
tb_basic.script: Test logic2: OK
tb_basic.script: Test logic3: OK
tb_basic.script: Test logic4: OK
tb_basic.script: Test logic5: OK
tb_basic.script: Test logic6: OK
tb_basic.script: Test logic7: OK
tb_basic.script: Test logic8: OK
tb_basic.script: Test logic9: OK
tb_basic.script: Test logic10: OK
tb_basic.script: Test logic11: OK
tb_basic.script: Test assign1: OK
tb_basic.script: Test assign2: OK
tb_basic.script: Test assign3: OK
tb_basic.script: Test assign4: OK
tb_basic.script: Test arr1: OK
tb_basic.script: Test arr2: OK
tb_basic.script: Test arr3: OK
tb_basic.script: Test arr4: OK
tb_basic.script: Test arr5: OK
tb_basic.script: Test arr6: OK
tb_basic.script: Test arr7: OK
tb_basic.script: Test arr8: OK
tb_basic.script: Test arr9: OK
tb_basic.script: Test arr10: OK
tb_basic.script: Test arr11: OK
tb_basic.script: Test arr12: OK
tb_basic.script: Test arr13: OK
tb_basic.script: Test arr14: OK
tb_basic.script: Test arr15: OK
tb_basic.script: Test shortcircuit1: OK
tb_basic.script: Test shortcircuit2: OK
tb_basic.script: Test shortcircuit3: OK
tb_basic.script: Test shortcircuit4: OK
tb_basic.script: Test shortcircuit5: OK
tb_basic.script: Test shortcircuit6: OK
tb_basic.script: Test shortcircuit7: OK
tb_basic.script: Test conditional1: OK
tb_basic.script: Test conditional2: OK
tb_basic.script: Test conditional3: OK
```

7. In relation to commits f21098d4ea63157bb719939e968c99e02769791d and bb4c2fa727c64ee5e3a7fe9753b48f236eaff16d, I used the job names listed here
https://github.com/danielyxie/bitburner/blob/dev/src/Company/data/companypositionnames.ts
to test those job names that should have the indefinite article "an".  It now works as expected.  See the attached images.  I opened ticket #4174 because I thought the current PR was already morbidly obese.  I had some working code and documentation, and waiting to clear my head first before I test them.  Both commits f21098d4ea63157bb719939e968c99e02769791d and bb4c2fa727c64ee5e3a7fe9753b48f236eaff16d, and my code in progress, currently handle the following job names:
```
IT Intern
IT Analyst
IT Manager
Operations Manager
Employee
```
And all 3 solutions have a potential flaw.  In commit bb4c2fa727c64ee5e3a7fe9753b48f236eaff16d, perhaps the lines
```js
/** returns "a" or "an" depending on whether the provided string starts with a vowel */
const aOrAn = (s: string) => (/^[aeiou]/i.test(s) ? "an" : "a");
```
can be prefixed with some documentation about the potential flaw and become:
```js
/**
 * Returns "a" or "an" depending on whether the provided string starts with a
 * vowel.
 *
 * The code below can fail if the input is a word that starts with a vowel but
 * should not be prefixed with "an", e.g. we usually write and say "a unit"
 * instead of "an unit". If in a future release a new job is added, e.g.
 * "Unit Manager" for a special operative team or "University Administrator",
 * then we write "a Unit Manager" instead of "an Unit Manager", and we write
 * "a University Administrator" instead of "an University Administrator".
 */
const aOrAn = (s: string) => (/^[aeiou]/i.test(s) ? "an" : "a");
```
If we are to use "an" to prefix each of the above job names, then we also have to think about other jobs that might be added in a future release.  We would then have to do some kind of pattern matching to determine whether we need the indefinite article "a" or "an".  A simple solution is to use the template:
```
You are currently working as [jobName] at [companyName].
```
The template covers most cases.  An exception to the above template is `Employee`.  This sounds awkward:
```
You are currently working as Employee at [companyName].
```
This makes sense:
```
You are currently working as an Employee at [companyName].
```
For now, we can use the fix in bb4c2fa727c64ee5e3a7fe9753b48f236eaff16d: decide whether to use "a" or "an" based on whether the job name starts with a vowel.

8. These are commits about which I'm unsure because they touch the source code and I don't know how to test.  Everthing else looks good.
    1. Commit e626b19db85c94a6d7b280a707ade66906a12f82 fixes the typo at bfdefbabe050f40ba40b122e6204a4de458d9b48 and also typos in function names.
    1. Commits f4252d2a956811d1dfd902c33e2844d53a7dbcb0, cfa4dc0ab7d52a9e4afffc8eb776041a4cfdc08a, fe7aeb96e2999f9dc6ecaed35f9ae525f8b35a4d, 1e0f4b84ee19f2b5d957999ef810aa5c5c615269, 46774721950296d5ea4bdb71bb81f0e9a1aeba39.
    1. Commits 8c04b5de456d2fda6402dedaffee41fceb36ab82, 3bdb4c5d2f62b25ee2b396a17f465a26e844ee35, 6c02bf41fbbe48bebd430e945db2e35311f37ec3, 7f49362eafe5fc626a634613f515833d96530f37 are cosmetic changes to conform to the coding standard of the source code (`npm run format`).
    1. Commits 4778f3941b96efa6d0d178a985bf785ecd89b5a3, e3815478fbf4d5a7ccdc7ee0e8c6e36d46cbe9a0, 82ae37ee9a879a57d8300cc6375e33d75051610b, eb18d2e3b537ab8b34a3d0d1222ac4bf428d4424.

9. A (perhaps unintentional) funny commit.  This commit 16c4420748b76e122b5719dab98ed3cf2050e33a advises people to live a moral life.  Here's another example where the game gives life advice: the world server `unitalife` is telling players to get a life outside of the game.
05_it-manager_work
05_it-manager_apply
04_operations-manager_work
04_operations-manager_apply
03_employee_work
02_it-analyst_work
02_it-analyst_apply
01_it-intern_work
01_it-intern_apply

**Comment by Snarling** [comment]
> 1. Running `npm run format` didn't report any issues.
> 2. The linter is happy now.  Running `npm run lint` no longer complains about unused import.
For both of these I was referring to the server side checks on github, on the "checks" tab of this PR or also shown on this discussion page. 
image

Here the linter fails because it expects us not to touch anything in the ThirdParty folder. The prettier check fails due to thinking something is wrong with ScriptEditorRoot.tsx even though `npm run format` does not see any issues there.
image

> Previously, I had one failed test due to PR #4141. Perhaps the project no longer use or care about the test suite?
This is correct, tests have not passed for any PRs in a very long time because the tests are broken. For a while we have just been ignoring them because no one has fixed the tests.

> 4. A number of glaring grammatical errors in the typo fixes.  However, those grammatical errors are not within the scope of this typo-police PR.  Grammatical errors belong to another, grammar police PR.
Grammar and typos can and I think should be fixed in the same PR. Otherwise if the PRs were to exist side by side, they would conflict on like everything and merging one would completely wreck the other since they probably touch a lot of the same stuff.

> And all 3 solutions have a potential flaw. In commit [bb4c2fa](https://github.com/danielyxie/bitburner/commit/bb4c2fa727c64ee5e3a7fe9753b48f236eaff16d), perhaps the lines
> 
> ```js
> /** returns "a" or "an" depending on whether the provided string starts with a vowel */
> const aOrAn = (s: string) => (/^[aeiou]/i.test(s) ? "an" : "a");
> ```
> 
> can be prefixed with some documentation about the potential flaw and become:
> 
> ```js
> /**
>  * Returns "a" or "an" depending on whether the provided string starts with a
>  * vowel.
>  *
>  * The code below can fail if the input is a word that starts with a vowel but
>  * should not be prefixed with "an", e.g. we usually write and say "a unit"
>  * instead of "an unit". If in a future release a new job is added, e.g.
>  * "Unit Manager" for a special operative team or "University Administrator",
>  * then we write "a Unit Manager" instead of "an Unit Manager", and we write
>  * "a University Administrator" instead of "an University Administrator".
>  */
> const aOrAn = (s: string) => (/^[aeiou]/i.test(s) ? "an" : "a");
> ```
I added some exceptions arrays and slightly more documentation, so that aOrAn can have hardcoded return values for specific "a-words" and "an-words." If the word wasn't on one of the hardcoded lists, it'll just use the regex. Those lists will be empty for now but can be added to if any use case for aOrAn (doesn't just have to be used for jobs, it's just the only current use) ends up actually needing the exceptions.

> 8. These are commits about which I'm unsure because they touch the source code and I don't know how to test.  Everthing else looks good.
>    
Mostly these are tested just by building the game. If I change the name of a function, then the game will fail to compile if I didn't also rename every reference to that function. I just looked at a couple of these and they look fine to me.

**Comment by quacksouls** [comment]
In 83683aff4dcd92046cf8cf1cd35ab6f656362745, the code looks good.  The TypeScript compiler is very lenient even without type annotation for the return type of the function `aOrAn()` and with the compiler switch `"strict": true`.  This seems at odds with other functions in the file, each of which has a return type.  In the line
```js
returns "a" or "an" depending on whether the provided string starts with a vowel.
```
is `returns` a keyword that will be picked up by the doc generator, hence it's written as lowercase?  Or should this be `Returns`?  Apart from the above nitpick, everything is good.

**Comment by Snarling** [comment]
> In [83683af](https://github.com/danielyxie/bitburner/commit/83683aff4dcd92046cf8cf1cd35ab6f656362745), the code looks good. The TypeScript compiler is very lenient even without type annotation for the return type of the function `aOrAn()` and with the compiler switch `"strict": true`. This seems at odds with other functions in the file, each of which has a return type. In the line
> 
> ```js
> returns "a" or "an" depending on whether the provided string starts with a vowel.
> ```
> 
> is `returns` a keyword that will be picked up by the doc generator, hence it's written as lowercase? Or should this be `Returns`? Apart from the above nitpick, everything is good.

No, typescript is not relying on any explicit declaration of type in order to determine the return type for aOrAn. Instead, it is looking inside the code, and seeing what the function is allowed to return, and setting the return type based on that.

In fact, it implicitly sets the type as the even more specific than string, as type `"a" | "an"`. That type still is a string and can be used anywhere that `string` works, but it can also work in more specific cases as well where custom types limit the available values:

image

But if you had an article type, you'd probably just set that explicitly as the return type for aOrAn for some type consistency.

Generally, I prefer to use implicit typing where possible if the explicit type would be redundant. Extra redundant type code is one of the reasons I used to hate typescript.

In many cases, `npm run lint` will actually remove unnecessary explicit type declarations from the code, e.g.

image

But it will not remove unnecessary type declarations for function return types.

There's certainly an argument for using explicit return types. It ensures that if you modify that function to return a different type (longshot in this case), you will get a type error on the function, instead of maybe getting a type error somewhere else where the function is used. In this particular use case where the implicit type is super specific (rare), it may also be confusing for some people seeing a type as `"a" | "an"` when they're expecting `string`, so that's another argument for explicit typing in this particular case.

**Comment by hydroflame** [comment]
Fixed MCs off screen.

**Pull request closed without merging**
