### PR TITLE
Update Remote API doc link

### PR DESCRIPTION
**Pull request by dhosborne**
Updated remote API Documentation link to point to https://github.com/danielyxie/bitburner/blob/dev/doc/source/remoteapi.rst

Tested 
- linter passed
- Compiled and run in browser. 
- Compiled with electron and run via .exe
- Link successfully opens browser window to https://github.com/danielyxie/bitburner/blob/dev/doc/source/remoteapi.rst

### CODE REVIEW

**Comment by phyzical** [comment]
@dhosborne please remove the dist files and the lock changes

**Comment by dhosborne** [comment]
My apologies. I am pretty new to this. I deleted the dist files.

What do you mean by "lock changes"? Like remove the package-lock.json file?

**Comment by dhosborne** [comment]
Removed

**Comment by phyzical** [comment]
sorry that is what i meant but i meant just dont commit those changes to those files, might be easier to create a new pr/branch 
image

basically you should see only 1 file changed if it was done right :)

**Comment by dhosborne** [comment]
I'm tracking now, thanks! I see there are 236 files deleted and 1 file changed. Do I need to do anything else?

**Pull request closed without merging**
