### PR TITLE
Implements 'ls -l' for single-column output

### PR DESCRIPTION
**Pull request by mikomyazaki**
Addresses #1944 

ls_list_output

### CODE REVIEW

**Comment by hydroflame** [comment]
uhhh, not quite, the codebase already has a flag parser that we can use to simplify a lot of this code.

**Comment by mikomyazaki** [comment]
Converted to use the flags parser.

There is another command `ps()` which uses the `| grep pattern` format for its arguments, do you want me to convert it to `--grep pattern` for consistency, in this PR? Or do it separately.

**Comment by hydroflame** [comment]
I want it converted to `--grep` because it's easier for the game to handle. Even though it does not make "real world" sense.

**Comment by hydroflame** [comment]
Ok so this isn't really using the flags library as intended, `-l` doesn't work. So I'm going to close this.

**Pull request closed without merging**
