### PR TITLE
added ram charge for stanek width and height

### PR DESCRIPTION
**Pull request by phyzical**
something noticed taking a stab at fixing the static ram calc issues

### CODE REVIEW

**Comment by hydroflame** [comment]
missing NetscriptDefinitions.d.ts

**Comment by phyzical** [comment]
image

i think its there, lmk if you mean something else 👍

**Comment by hydroflame** [comment]
Ah, that's my real name :(

**Comment by phyzical** [comment]
@hydroflame  ah sorry, itll be your git config on a computer somewhere (proably your work pc 😆) same thing happens with me when i switch between my home pc and work pc

**Pull request merged**
