### PR TITLE
correct tax calculation of corporation dividends

### PR DESCRIPTION
**Pull request by Yirka**
This PR attempts to fix the inconsistent dividend tax rates.

To begin with, the game uses the following formula to calculate dividends after taxes:
```
return Math.pow(dividends, BitNodeMultipliers.CorporationSoftCap + upgrades);
```
Where (with values from my corporation)
```
dividends = 107718488.83520724
BitNodeMultipliers.CorporationSoftCap = 1
upgrades = -0.15
```
Yields the mathematical expression
```
107718488.83520724^0.85 = 6721198.38429
```
Which is 
```
6721198.38429 / 107718488.83520724 = 0.0624
or
93.76% effective tax rate
```
This 93.76% tax rate is far, far off the `dividendTaxPercentage = 50;`found within the same file.

Additionally, having had both of the upgrades (reducing tax by 5% and 10% respectively) would've changed the expression to:
```
107718488.83520724^1 = 107718488.83520724
```
Which, quite obviously, is the equivalent of paying _**no tax at all**_, rather than the expected 35%

As such, I propose the formula to be changed to:
```
return Math.pow(dividends, BitNodeMultipliers.CorporationSoftCap) * (1 - (this.dividendTaxPercentage / 100));
```
Alternatively (but more disruptively),
```
return dividends * BitNodeMultipliers.CorporationSoftCap * (1 - (this.dividendTaxPercentage / 100));
```

This change maintains the power relation between dividends and BitNodeMultipliers.CorporationSoftCap, but changes the taxes to scale more linearly with upgrades.
As a consequence, this makes corporation dividends much more profitable early game (50% tax instead of >90%), but much less profitable late game (35% tax instead of 0%).

I've looked through past commits, but wasn't able find any reference to this.
This leaves the possibility that this behavior is 100% inteded, and the problem lies within the user interface rather than the formulas.

Furthermore, with both upgrades present I've identified in the overview that dividends per second are an order of magnitude greater than my actual income.
This is because the dividends get calculated once every 10 seconds, but the overview pretends that this happens once per second instead.

image

fixes https://github.com/danielyxie/bitburner/issues/2261

### CODE REVIEW

**Comment by pigalot** [comment]
I would vote to reject this as it is effectively a nerf on corps and the current code looks fairly intended to me.

A good bug fix would be to fix the UI.

**Comment by Yirka** [comment]
The problem with fixing the UI is that this issue is practically indescribable without putting the formula directly within the dividends display and hoping that the player will understand what it means. This is a problematic solution when understanding isn't guaranteed due to the effective tax rate approaching either 100% or 0% depending on upgrades and/or bitnode multipliers.

**Comment by pigalot** [comment]
Your solution is more problematic, directly nerfing corps without fixing any of its 100s of problems is pointless.

**Comment by phyzical** [comment]
(fyi no one is dissing your solution) we just know that it would become a problem again and then we need to understand another concoction of variables to fix the issue that could just be resolved in another way.

or rather lets say in a month we do balance corps, then we need to rework this again. but maybe there's another contributor that does it and misinterprets something.

all just to fix a ui bug 😆, and at the end of the day we can just make such big decisions those are up to higher powers

**Comment by hydroflame** [comment]
The UI needs fixing but the code is correct. This is meant to have harsh diminishin return.

**Pull request closed without merging**
