### PR TITLE
CORP: fixed wrongly named division type

### PR DESCRIPTION
**Pull request by Mughur**
"Computer" division type was erroneously named "Hardware" in the constants.
Division types list is only called by the getDivisionTypes ns function, so the bug didn't cause issues

### CODE REVIEW

**Comment by phyzical** [comment]
it is called software though isnt it? 
image
image

**Comment by phyzical** [comment]
oh maybe it should be Computer is missing?

**Comment by Mughur** [comment]
> oh maybe it should be Computer is missing?

computer <-> hardware was the issue

**Comment by phyzical** [comment]
Ah updated the wrong constant :D

**Comment by Mughur** [comment]
oh ffs

**Review by phyzical — APPROVED** [review]

**Pull request merged**
