### PR TITLE
Suggestion: Change Ram-Formatting to IEC 60027-2

### PR DESCRIPTION
**Pull request by Hedrauta**
Just an idea <.<
pic

### CODE REVIEW

**Comment by MageKing17** [comment]
RAM can't be measured in GiB, because then functions would cost fractional bytes (0.05 GiB is 53687091.2 bytes).

**Comment by Hedrauta** [comment]
🤔  what do you mean? it's still fine.... just the suffix will change
pic

**Comment by Hedrauta** [comment]
oh... !
no... everything starts at GiB... just the counting up to TiB, PiB & EiB will change

**Comment by Hedrauta** [comment]
or... to be more clear: there is no "MiB" or "KiB" used in the game 😉 otherwise, i would have respect that one ;)

**Comment by MageKing17** [comment]
> 🤔 what do you mean? it's still fine.... just the suffix will change

The point is that the suffix wouldn't make *sense*: 1.60 GiB is 1.6 * 1024 * 1024 * 1024 bytes, or 1717986918.4 bytes, and ".4 bytes" is a nonsensical value (it would be 3.2 bits). Whereas 1.60 GB is 1.6 * 1000 * 1000 * 1000 bytes, and one billion six hundred million bytes is a perfectly valid value.

**Comment by Hedrauta** [comment]
> The point is that the suffix wouldn't make _sense_: 1.60 GiB is 1.6 * 1024 * 1024 * 1024 bytes, or 1717986918.4 bytes, and ".4 bytes" is a nonsensical value (it would be 3.2 bits). Whereas 1.60 GB is 1.6 * 1000 * 1000 * 1000 bytes, and one billion six hundred million bytes is a perfectly valid value.




> or... to be more clear: there is no "MiB" or "KiB" used in the game 😉 otherwise, i would have respect that one ;)

it's just for the eyes..... or you want get shown 1.04PB servers ? 
🤔 ... maybe only change the formatting AFTER the GB, so it would be GB, TiB, PiB and EiB .... then, everything would be fine "in your opinion"... just the math above GB would change....

**Pull request closed without merging**
