### PR TITLE
INFILTRATION: Slash minigame fixed so attacking when the guard is preparing doesn't cause failure, fixed indicator when player has Might of Ares augmentation

### LINKED ISSUE #4125: "Slash when his guard is down!" actually means "Slash when he's attacking!" Also the Might of Ares timer is wrong.
If the guard is *preparing* to attack, his guard is down as far as regular English is concerned: he's no longer "guarding." I would also assume that attacking during the "preparing" phase would mean that I wouldn't take damage from his attack, therefor more preferable (then again, being reduced to 0 doesn't seem to...do anything either; I've actually started a new infiltration with 0 health and taken damage with no ill effects).

But slashing when he's 'preparing' is considered a failure:
https://github.com/danielyxie/bitburner/blob/dev/src/Infiltration/ui/SlashGame.tsx#L36
https://github.com/danielyxie/bitburner/blob/dev/src/Infiltration/ui/SlashGame.tsx#L76

Additionally, if you have the WKS harmonizer augmentation, the Might of Ares timer is wrong, because of this line:
https://github.com/danielyxie/bitburner/blob/bcbda22acc1a5afb5aaa9472e2d29947fe867952/src/Infiltration/ui/GameTimer.tsx#L16

It takes the `phaseZeroTime + phaseOneTime` time passed in...and adds 30%...

- [x] Version of the game, e.g. Bitburner v2.0.2

### PR DESCRIPTION
**Pull request by connertennery**
# Summary
- Added ignoreAugment_WKSharmonizer to GameTimer to allow for strict, unmodified timers
- Changed SlashGame failure check
- Changed `timeUntilAttacking` value so the progress bar in SlashGame is accurate

# Linked issues

fixes #4125 

# Bug fix

The fix was simple enough; the issue pointed to the places in code that needed to be updated. The GameTimer for the progress bar in SlashGame was using the phaseZero and phaseOne times combined instead of just phaseZero. Changing the failure check from 2 to 1 fixed the incorrect mechanic of attacking when the guard was down.

## Testing
**Failure**
1. Start the SlashGame
2. Attack when the Guard is guarding to fail

**Success**
1. Start the SlashGame
2. Observe the progress bar end right at the end of phaseZero, indicating when to attack
3. Attack the guard to win

## Preview

https://user-images.githubusercontent.com/16765522/193537861-7590fd4a-23d8-4380-ab32-964cbfdc8537.mov

### CODE REVIEW

**Comment by Draco18s** [comment]
Only reason I haven't delved into making PRs myself is I'm having too much fun playing *the game.* :p But have certainly considered it.

I also wasn't sure how to handle fixing the Might of Ares issue, looking at how you handled it, that is an excellent solution.

**Comment by connertennery** [comment]
Thanks! I'm usually too busy working to have the free time to play games or make PRs, but there's been a recent slow down at work so I thought I'd try to fix something. Bitburner is a great background game once you get the Singularity API lol.

**Comment by Draco18s** [comment]
Or really, any time and want to look busy writing code. ;)
I'm currently on my second node, BN3, so I'm running into all of the deficiencies in the API for corps.

**Comment by Draco18s** [comment]
@hydroflame appears this commit introduced a case-sensitive compilation bug.

I got the following when validating my own PR after the recent merges:

	Issues checking in progress...
	ERROR in src/Infiltration/ui/GameTimer.tsx:17:44
	TS2552: Cannot find name 'player'. Did you mean 'Player'?
		15 |   const [v, setV] = useState(100);
		16 |   const totalMillis =
	  > 17 |     (!props.ignoreAugment_WKSharmonizer && player.hasAugmentation(AugmentationNames.WKSharmonizer, true) ? 1.3 : 1) *
		   |                                            ^^^^^^
		18 |     props.millis;
		19 |
		20 |   const tick = 200;

As well as another error that shows up at the end of the file, `TS1128: Declaration or statement expected.`

**Pull request merged**
