### PR TITLE
Cache the blobs generated by scripts

### PR DESCRIPTION
**Pull request by theit8514**
When running a script, generate a hash of the code used by that script. If that hash is in our blob cache, we reuse the blob URL. If not, a new blob is generated and stored in the cache.

Some notes:
* This still has the issue that scripts are recompiled on soft reset, but the hash of the script should not change, so the blobs and ScriptUrls will still be the same.
* We are no longer calling URL.revokeObjectURL on URLs since they could be in use by another script. This will leave blob URLs leaked on occasion, but that leaking should be at a minimum with the cache. As far as I can tell, URL.revokeObjectURL doesn't remove the URL from the DevTools anyways, so those URLs are in memory somewhere.
  * Example, this only generates 4 blobs total (1 for the main script, 1 for helpers.js, and one each for the flip/flop):
   ```js
    import {
        getNsDataThroughFile
    } from './helpers.js'
    
    /** @param {NS} ns */
    async function getCurrentFactionFavour(ns, factionName) {
        return await getNsDataThroughFile(ns, `ns.getFactionFavor('${factionName}')`, '/Temp/faction-favor.txt');
    }
    
    /** @param {NS} ns **/
    export async function main(ns) {
        while (true) {
            let currentFavor = await getCurrentFactionFavour(ns, "Bachman & Associates");
            ns.tprint(currentFavor);
            currentFavor = await getCurrentFactionFavour(ns, "Sector-12");
            ns.tprint(currentFavor);
            await ns.sleep(5000);
        }
    }
    ```
* Scripts running across multiple servers or multiple filenames with the same hash will have the same blobs, so this necessitated a change with how we lookup blob urls to script name mappings.
* A 3rd party library is imported for sha256 hashing since the browser based hashing method is async and we needed synchronous calculation of the hash in several places.

### CODE REVIEW

**Comment by smolgumball** [comment]
@theit8514 I am running into a stale dependency issue where if an imported script is updated, the parent doesn't pick up on the changes. Internally, the `_.hash` property of the `Script` object is updating, but whatever mechanism is used for caching the blobs is causing the old blob to be reused rather than the newly regenerated one.

Really not sure how best to package my findings for you to reproduce, but I can try if needed, just let me know!

**Comment by paulcdejean** [comment]
@hydroflame can this maybe be reverted while a better implementation is worked on? This has been causing headaches to basically anyone who tries to play without using a rollup process...

https://github.com/bitburner-official/bitburner-vscode/issues/10
https://github.com/danielyxie/bitburner/issues/2413
https://github.com/danielyxie/bitburner/issues/2336
https://github.com/danielyxie/bitburner/issues/2408
https://github.com/danielyxie/bitburner/issues/2443

I've been needing to do this workaround, modifying the bundle file every time there's an update:

> It seems like you can disable to import cache check by editing the main bundle ( \Bitburner\resources\app\main.bundle.js) and replacing
`l||(l=_getScriptUrls(s,t,a))`

> with
`(l=_getScriptUrls(s,t,a))`

**Comment by paulcdejean** [comment]
Basically I think the performance gains here benefit a small number of players while the buggy behavior caused by the incomplete implementation is affecting a lot of people.

**Comment by tvanderpol** [comment]
I'd at least really appreciate a toggle - I'd be very happy to eat a performance impact if that meant I was always running the code I thought I was running.

**Comment by Domanoc** [comment]
I would even go for an option to have a netscript command to clear the cache of a specific script/blob then we could manually clear chained imports while scripting. Without having to go in roundabout ways of updating or reloading the game.

**Pull request merged**
