### PR TITLE
Added getDarkwebProgramCost and related unit tests to the api. 

### PR DESCRIPTION
**Pull request by neuralsim**
Gets the price of a specified darkweb program.

```js
let price = ns.getDarkwebProgramCost("brutessh.exe");
// get the price

ns.tprint(price);
// print the price to the terminal. Will output -1 if Tor has not been purchased, 
// otherwise will print 500000 if brutessh.exe has not been purchased yet, or 
// 0 if it has already been purchased. 

price = ns.getDarkwebProgramCost("bogusProgram.exe");
// throws an exception, since bogusProgram.exe isn't a darkweb program 
```

The reasoning for throwing an error if the program name is incorrect is that 99% of the time, if players get the name of the program wrong, it's probably the first time they've tried to execute the script, so giving them a big fat error will help with rapid debugging.

I followed the example of purchaseProgram in terms of the unit tests I created, and for the documentation.

### CODE REVIEW

**Comment by alainbryden** [comment]
I feel like hard-coding the costs of these programs is easier than hard coding the names (with the correct casing). I would propose that this function on its own is not useful unless you are also adding an API for getting the names of the dark web programs.

**Comment by neuralsim** [comment]
I did add a function to get the names

**Comment by neuralsim** [comment]
> I feel like hard-coding the costs of these programs is easier than hard coding the names (with the correct casing). I would propose that this function on its own is not useful unless you are also adding an API for getting the names of the dark web programs.

See PR #2662

**Review by phyzical — APPROVED** [review]
LGTM

**Comment by hydroflame** [comment]
Included elsewhere

**Pull request closed without merging**
