### PR TITLE
Comp. Rep. Focus Fix

### PR DESCRIPTION
**Pull request by Tesseract1234567890**
This was brought to my attention by kwazygloo

### CODE REVIEW

**Comment by hydroflame** [comment]
Uh, applying for a new job shouldn't reset your work status.

**Comment by Tesseract1234567890** [comment]
That should only do it if the player gets the new job.

**Comment by hydroflame** [comment]
Right, but getting a new job isn't the issue. The issue is that the rep is transfered.

**Comment by Tesseract1234567890** [comment]
This should fix the reputation being transferred. Additionally, it will cancel the job if the player is accepted into a new job.

**Pull request closed without merging**
