### PR TITLE
Fix #1880: Show git commit of bundled app

### LINKED ISSUE #1880: game shoudl show git commit version that it's running on.

### PR DESCRIPTION
**Pull request by MartinFournier**
Shows the git commit using webpack bundle defines in the topbar, loading screen & terminal.

### CODE REVIEW

**Comment by hydroflame** [comment]
That is awesome!

Do I need to commit first and then build?

**Comment by MartinFournier** [comment]
Yeah, it runs git rev-parse --short HEAD, so you'll need to commit then build.

**Comment by MartinFournier** [comment]
Oh wait I typo'd something

**Comment by hydroflame** [comment]
We good? You fixed your typo?

**Pull request merged**
