### PR TITLE
Present offline message as list

### PR DESCRIPTION
**Pull request by DSteve595**
I just recently started playing. After taking a quick break and starting the game again, I got this message:

image

The info's great, but the bit about the unchanged reputation is redundant, and irrelevant to new players that already have a bunch of new concepts to wrap their heads around. I think showing this info as a list would solve a bunch of little problems here.

image

- More glanceable
- ~Conditionally shows reputation~
  - Scrapped this. Could cause confusion of its own.
- Fewer changes needed if/when another element is added

Awesome game by the way!

### CODE REVIEW

**Comment by phyzical** [comment]
hmmmm i like the changes much cleaner, but i feel like we should show 0.00 rep as it just makes it more obvious that they earned no rep.

i get the "dont over confuse new users" but you will still end up finding out about rep even before exiting your first bitnode.

if you reaaallly wanted to fight for this, maybe we can check if they have ever earned any repuation before? then show it rather than basing it on if there was any offline earnings?

**Review by phyzical — APPROVED** [review]
lgtm just the one comment about always hiding 0.00 rep

**Comment by DSteve595** [comment]
>check if they have ever earned any repuation before

I think this is totally ideal. I don't know enough about the project to know how to hook this up, though.
Changed the reputation to be unconditional.

**Comment by phyzical** [comment]
👍  i had a quick scan and there isnt any magical functions to work this out, it would require looping all factions to call `getFactionRep` and looping all companies to check `getCompanyRep"

If your feeling up for it it would be something along the lines of the following

```
const hasAnyRep = (Factions.reduce((factionName) => getFactionRep(factionName)) + Companies.reduce((companyName) => getCompanyRep(companyName))) > 0
```

**Pull request merged**
