### PR TITLE
Update `<Tabs>` sizing and style

### PR DESCRIPTION
**Pull request by nickofolas**
Adjusts the style of all `<Tabs>` and `<Tab>` elements to match the design of script editor tabs.

Also updated the sizing of the tabs on the Active Scripts, Corp, and Gang page [to be more conducive to the way the average user reads the page](https://canary.discord.com/channels/415207508303544321/459097632896188436/933494038382927922)

### Active Scripts sizing

<table>
  <th>Before</th>
  <th>After</th>
  <tr>
    <td>
    </td>
    <td>
    </td>
  </tr>
</table>

### Corps tabs sizing

<table>
  <th>Before</th>
  <th>After</th>
  <tr>
    <td>
    </td>
    <td>
    </td>
  </tr>
</table>

### Gangs tabs sizing

<table>
  <th>Before</th>
  <th>After</th>
  <tr>
    <td>
    </td>
    <td>
    </td>
  </tr>
</table>

### All Tabs styling

<table>
  <th>Before</th>
  <th>After</th>
  <tr>
    <td>
    </td>
    <td>
    </td>
  </tr>
</table>

New tab style applies to all areas where these components are used:
- Active scripts
- Gangs
- Corps
- Bladeburner

Tested on Firefox 97.0

### CODE REVIEW

**Comment by smolgumball** [comment]
looks good to me, so much easier to get a sense of the UI, especially when on a particularly widescreen monitor

**Comment by nickofolas** [comment]
Updated to resolve the merge conflict!

**Review by phyzical — APPROVED** [review]
LGTM

But the one thing that feels wrong to me is the fact we don't allow it to expand to the space available?

shouldn't we allow this for when the screen as shrunk responsive wise but for people with larger screens why not allow tabs to fit to the space?

**Comment by nickofolas** [comment]
See the discussion linked in the original PR. Placing tabs towards the left is more conducive to the way people quickly scan a page, whereas stretching to fill the page is more likely to lead to people missing things (the PR was originally prompted by the fact that people can rather easily miss the fact that the recent scripts tab exists).

**Comment by ChrissiQ** [comment]
This makes sense and is a useful feature.  Can someone just confirm that none of the affected interfaces break at high zoom levels?   Would hate to find that this breaks when zooming, this is very important for several people playing with reduced vision.

**Comment by nickofolas** [comment]
Here are examples of all of the tabs at 190% zoom, hopefully that helps!

image

image

image

image

**Pull request merged**
