### PR TITLE
Todo: add more crimes

### PR DESCRIPTION
**Pull request by JimboSwaggins**
More like toDONE.
I'm not super used to javascript (I code java), so the protection services is commented out. Other than that, just a few crime types added (Clone trafficking could be changed to human trafficking, wanted to keep it PG-13) 

- Added AI trafficking, the digital equivalent of human trafficking
- Added Clone trafficking, the physical equivalent of AI trafficking
- Partially added protection services, where gang members extort money for protection. Higher territory = higher money and risk, risk can be offset by recruiting more members (Because otherwise your army gets stretched too thin to logistically extort over larger areas)

### CODE REVIEW

**Comment by SloopLiztmin** [comment]
I don't know how to use NPM, I've never used it before. Sorry, like I said, I code java normally, so I use eclipse and run things as .jars normally. I'm trying to download NPM right now.

**Comment by SloopLiztmin** [comment]
Yeah I have no idea how to use this thing, I'm just going to leave these here so that you guys can decide if you want them in

**Comment by hydroflame** [comment]
no please don't check in the bundle, itll cause a million merge conflict, just check in the bundle as part of every release

**Comment by hydroflame** [comment]
You can generate the bundle and run it locally but not check it in.

**Comment by kopelli** [comment]
You can...and you can also fork & edit directly in the Github interface. And without many automated tests that the pull request engine can use to verify the integrity of the changes it's on the shoulders of the repository owner to manually test the changes don't have bad syntax/logic. At least when the bundle is included it's a clear sign that the changes have been run locally via webpack to properly rebuild the bundle.

And since bundle is already being tracked, it seems an odd practice (at least to me) to not include it as part of the files being modified as part of a change. Doesn't matter if it's a separate commit or part of a the "single" change, including the bundled output seems like it should be part of the standard contribution workflow.

Although this really touches on a different issue in that the bundled code (HTML, CSS, and bundled JS) should really be in a separate branch (like `gh-pages`) and the game URL should be pointed to that branch. Then the releases are isolated to just that branch, rather than the bundle being intermixed with the source updates.

**Comment by hydroflame** [comment]
You're right.

**Comment by danielyxie** [comment]
(Somewhat) added as part of upcoming gang-rework

**Pull request closed without merging**
