### PR TITLE
feat(ns): add function to print link to server

### PR DESCRIPTION
**Pull request by billyvg**
This is kind of janky because it only prints on a newline.

### CODE REVIEW

**Comment by billyvg** [comment]
thoughts?

**Comment by hydroflame** [comment]
nope

**Comment by billyvg** [comment]
@hydroflame any reason why?

**Comment by hydroflame** [comment]
It removes puzzles from the game.

**Comment by hydroflame** [comment]
oh ... not really

**Comment by hydroflame** [comment]
Gonna close because autolink will let you connect anywhere

**Pull request closed without merging**
