### PR TITLE
Removing old comment about removed parameter

### PR DESCRIPTION
**Pull request by Xynrati**
Because "no it don't"

### CODE REVIEW

**Review by Hedrauta — APPROVED** [review]

**Comment by hydroflame** [comment]
Not gonna work though because NetscriptDefinitions.d.ts needs to be changed.

**Comment by Hedrauta** [comment]
🤔 Oh... Didn't saw the filename....

**Comment by Hedrauta** [comment]
Still not gonna work 🙃

**Comment by Xynrati** [comment]
> Still not gonna work 🙃

:( what did I miss?

**Comment by Hedrauta** [comment]
Edit this file : https://github.com/danielyxie/bitburner/blob/dev/src/ScriptEditor/NetscriptDefinitions.d.ts
Markdown folder is automatically created and updated by tjis file ( + a few more)

**Comment by Xynrati** [comment]
> Edit this file : https://github.com/danielyxie/bitburner/blob/dev/src/ScriptEditor/NetscriptDefinitions.d.ts Markdown folder is automatically created and updated by tjis file ( + a few more)

Did I not already do that? I'm confused...

**Comment by Hedrauta** [comment]
Oh..  Ye.. But your latest pushes included changes on the actual autocreated .MD-files.... 😏

**Pull request merged**
