### PR TITLE
Enhance api server

### PR DESCRIPTION
**Pull request by lordducky**
- Used restful patterns for handling server calls (GET/PUT/DELETE)

- Utilized Server interface for saves rather than re-implementing code

- Exposed operations for getting code-base of scripts on the home server and deleting files.

- Added a common response structure

### CODE REVIEW

**Review by surdaft — APPROVED** [review]
Looks good! Would be nice to be able to trust VSCode to delete the "- Copy" files when I copy/paste a file and then rename it. :')

**Comment by smolgumball** [comment]
looks great, would love to be able to do a proper bi-directional sync w/ the vscode extension and this feels like solid progress to that end

**Review by surdaft — APPROVED** [review]
Dang, good spot! Missed that when reviewing.

**Comment by lordducky** [comment]
> looks great, would love to be able to do a proper bi-directional sync w/ the vscode extension and this feels like solid progress to that end

I was looking to get to that point. I'm looking to hit a nice middle ground for the moment. But if you ask me, the proper approach to this would be a websocket model.

Right now the communication is omnidirectional (VScode making requests to the bitburner http server), but for true bidirectional communication, you would ideally use a websocket layer to stream events between the VScode client and the Bitburner web client so that terminal changes are also picked up.

But that would mean a big rewrite of the vscode module and the api-server as it stands.

**Comment by lordducky** [comment]
@surdaft Made one more addition, added ramUsage and hash as part of the returns.

This probably is needed for dirty checking based on my own dev-server prototypes around these changes.

**Review by surdaft — APPROVED** [review]

**Pull request merged**
