### PR TITLE
♿️  (Bitverse UI: Portal Button Accessibility) Makes clickable element into button.

### PR DESCRIPTION
**Pull request by ChrissiQ**
Clickable elements in a page which are not hyperlinks to other pages should be buttons for accessibility. This changes the clickable area into a button to more closely align with best practices.

### CODE REVIEW

**Comment by phyzical** [comment]
@ChrissiQ thanks for the contribution any chance of a gif that shows it working? (if not i can check out your branch and get it up for you :) )

**Comment by ChrissiQ** [comment]
@phyzical Yeah, there's no visual change at all - this is only an accessibility change.  So I'm not sure if a recording would be helpful at all since there's, uh, nothing new to see!

**Review by phyzical — APPROVED** [review]
LGTM assuming the gif shows it working as intended for non accessibility users

**Comment by ChrissiQ** [comment]
Sorry about the delay in getting back to you, thanks for your attention to this issue @phyzical.  Here's a video of the buttons working with the same appearance as before.

https://user-images.githubusercontent.com/1127719/154870627-f587a727-441a-4f8e-a8a4-3174e018a064.mov

**Comment by ChrissiQ** [comment]
I see the other issue for accessibility in the same area that was opened.  I'm not sure if I'll have time but I might be able to take a look at what they did and see how we can integrate these changes together.

**Comment by phyzical** [comment]
yeah i him know on discord and suggested he replicate your changes into his, he just removed the ascii and made them buttons. 

do you know if there's an "accessibility" way to do like the alt text for a button? or does the altext just appear?

**Review by phyzical — APPROVED** [review]

**Comment by ChrissiQ** [comment]
Yes, `aria-description` or `aria-describedby` can be used.  I am taking a look to see how that might be applied here.

**Comment by ChrissiQ** [comment]
I merged @TheMas3212's update for disabled ASCII art into my changes, and then further updated:
- changed labels to describe the bitnode - "Enter bitnode" was not correct, the button did not enter the bitnode but rather triggered the modal with the full description of the bitnode.
- added `aria-description` where applicable
- made tooltip work in both modes (disabled ASCII doesn't mean disabled tooltips, probably?  And both should be accessible with buttons, labels and descriptions)

Adding video in a sec.

**Comment by ChrissiQ** [comment]
Dev tools is open to show `aria` attributes.

ASCII art enabled:

https://user-images.githubusercontent.com/1127719/154875498-19503b57-e410-468d-8169-65bd88402845.mp4

ASCII art disabled:

https://user-images.githubusercontent.com/1127719/154875584-c25467fa-0a16-4ef5-8e5f-0d6f94ccb6e9.mp4

**Comment by ChrissiQ** [comment]
Sorry for force pushing, I had made a real mess of things.  It should be all happy now though, I hope!

**Comment by TheMas3212** [comment]
looks good to me

**Review by phyzical — APPROVED** [review]

**Comment by phyzical** [comment]
thanks gang LGTM

**Pull request merged**
