### PR TITLE
Fix logic of gang territory reaching limits

### PR DESCRIPTION
**Pull request by TheRealMaxion**
Fix the mixup of this and other that seems to have occurred sometime in the past of this code.

### CODE REVIEW

**Comment by TheRealMaxion** [comment]
It seems none of the failed tests have anything to do with this, and may be related to some bugs in those systems or tests?
Namely, ram calculation, and number formatting.

**Comment by phyzical** [comment]
correct failing tests are in master

**Comment by phyzical** [comment]
there is another issue hydro wants this to move towards ints instead of 0 to 1

**Comment by TheRealMaxion** [comment]
Ah right. This is just to fix the issue that has been in the code for a long time, where one of the lines even got removed recently.

**Comment by phyzical** [comment]
only problem is i think it only makes more territory lost in the meantime is all, dont think it would help right?

**Comment by TheRealMaxion** [comment]
Fair point. I've fixed it to ensure no territory disappears now.

**Comment by hydroflame** [comment]
Fixed some other way.

**Pull request closed without merging**
