### PR TITLE
fix typo (UnforTunately) fix #2918

### LINKED ISSUE #2918: Typo when stats do not match job requirements
Reads Unforunately where it should be Unfor_t_unately.

### PR DESCRIPTION
**Pull request by fwolfst**
User visible typo fix

### CODE REVIEW

**Comment by phyzical** [comment]
just wanted to note i've fixed this as part of #2913 refactor

**Comment by fwolfst** [comment]
> just wanted to note i've fixed this as part of #2913 refactor

Ya, repeating the string all over the place looked smelly to me too, but I did not want to fiddle with a JS/TS codebase.

**Comment by fwolfst** [comment]
> just wanted to note i've fixed this as part of #2913 refactor

Not sure how fast your PR will get merged, a rebase to my changes should be trivial. Feel free to close PR and ticket otherwise.

**Comment by phyzical** [comment]
👍 all good ill deal with  conflicts if i lose

**Review by phyzical — APPROVED** [review]

**Pull request merged**
